from pathlib import Path

import streamlit as st


st.title("Reports")

st.write(
    "Access and download the financial analytics reports "
    "generated by the Nifty 100 Analytics platform."
)


PROJECT_ROOT = Path(__file__).resolve().parents[3]

OUTPUT_DIR = PROJECT_ROOT / "output"
REPORTS_DIR = PROJECT_ROOT / "reports"
RADAR_DIR = REPORTS_DIR / "radar_charts"


# -------------------------------------------------------------------
# Screener Report
# -------------------------------------------------------------------

st.divider()
st.subheader("Screener Report")

screener_file = OUTPUT_DIR / "screener_output.xlsx"

if screener_file.exists():

    st.success(
        "Screener workbook is available."
    )

    with open(screener_file, "rb") as file:
        st.download_button(
            label="Download Screener Workbook",
            data=file,
            file_name=screener_file.name,
            mime=(
                "application/vnd.openxmlformats-officedocument."
                "spreadsheetml.sheet"
            ),
        )

else:
    st.warning(
        "Screener workbook not found."
    )


# -------------------------------------------------------------------
# Peer Comparison Report
# -------------------------------------------------------------------

st.divider()
st.subheader("Peer Comparison Report")

peer_file = OUTPUT_DIR / "peer_comparison.xlsx"

if peer_file.exists():

    st.success(
        "Peer comparison workbook is available."
    )

    with open(peer_file, "rb") as file:
        st.download_button(
            label="Download Peer Comparison Workbook",
            data=file,
            file_name=peer_file.name,
            mime=(
                "application/vnd.openxmlformats-officedocument."
                "spreadsheetml.sheet"
            ),
        )

else:
    st.warning(
        "Peer comparison workbook not found."
    )


# -------------------------------------------------------------------
# Screener Report
# -------------------------------------------------------------------

st.divider()
st.subheader("Nifty 100 Screener Report")

nifty_report = REPORTS_DIR / "nifty100_screener.xlsx"

if nifty_report.exists():

    st.success(
        "Nifty 100 report is available."
    )

    with open(nifty_report, "rb") as file:
        st.download_button(
            label="Download Nifty 100 Report",
            data=file,
            file_name=nifty_report.name,
            mime=(
                "application/vnd.openxmlformats-officedocument."
                "spreadsheetml.sheet"
            ),
        )

else:
    st.warning(
        "Nifty 100 report not found."
    )


# -------------------------------------------------------------------
# Radar Charts
# -------------------------------------------------------------------

st.divider()
st.subheader("Company Radar Charts")

if RADAR_DIR.exists():

    radar_files = sorted(
        RADAR_DIR.glob("*_radar.png")
    )

    st.metric(
        "Available Radar Charts",
        len(radar_files),
    )

    if radar_files:

        selected_radar = st.selectbox(
            "Select Company",
            radar_files,
            format_func=lambda path: (
                path.stem.replace("_radar", "")
            ),
        )

        st.image(
            selected_radar,
            caption=selected_radar.stem.replace(
                "_radar",
                "",
            ),
            use_container_width=True,
        )

        with open(selected_radar, "rb") as file:
            st.download_button(
                label="Download Radar Chart",
                data=file,
                file_name=selected_radar.name,
                mime="image/png",
            )

else:
    st.warning(
        "Radar chart directory not found."
    )
